name: Build toolchains only

on:
  workflow_dispatch:
    inputs:
      binutils_branch:
        description: 'Binutils branch to build'
        required: false
        default: 'woarm64'
      gcc_branch:
        description: 'GCC branch to build'
        required: false
        default: 'woarm64'
      mingw_branch:
        description: 'MinGW branch to build'
        required: false
        default: 'woarm64'
      cygwin_branch:
        description: 'Cygwin branch to build'
        required: false
        default: 'woarm64'
      cygwin_packages_branch:
        description: 'Cygwin packages branch to build'
        required: false
        default: 'main'
      cocom_branch:
        description: 'COCOM branch to build'
        required: false
        default: 'master'
      openblas_branch:
        description: 'OpenBLAS branch to test'
        required: false
        default: 'develop'
      openssl_branch:
        description: 'OpenSSL branch to test'
        required: false
        default: 'fix-tests'
  workflow_call:
    inputs:
      binutils_branch:
        type: string
      gcc_branch:
        type: string
      mingw_branch:
        type: string
      cygwin_branch:
        type: string
      cygwin_packages_branch:
        type: string
      cocom_branch:
        type: string
    outputs:
      toolchain-package-name:
        value: ${{ jobs.build-toolchain.outputs.toolchain-package-name }}
      toolchain-artifact-name:
        value: ${{ jobs.build-toolchain.outputs.toolchain-artifact-name }}
      runtime-package-name:
        value: ${{ jobs.build-toolchain.outputs.runtime-package-name }}
      runtime-artifact-name:
        value: ${{ jobs.build-toolchain.outputs.runtime-artifact-name }}
      toolchain-cache-key:
        value: ${{ jobs.build-toolchain.outputs.toolchain-cache-key }}
      runtime-cache-key:
        value: ${{ jobs.build-toolchain.outputs.runtime-cache-key }}

env:
  BINUTILS_REPO: Windows-on-ARM-Experiments/binutils-woarm64
  BINUTILS_BRANCH: ${{ inputs.binutils_branch || 'woarm64' }}

  GCC_REPO: Windows-on-ARM-Experiments/gcc-woarm64
  GCC_BRANCH: ${{ inputs.gcc_branch || 'woarm64' }}

  MINGW_REPO: Windows-on-ARM-Experiments/mingw-woarm64
  MINGW_BRANCH: ${{ inputs.mingw_branch || 'woarm64' }}

  CYGWIN_REPO: Windows-on-ARM-Experiments/newlib-cygwin
  CYGWIN_BRANCH: ${{ inputs.cygwin_branch || 'woarm64' }}

  CYGWIN_PACKAGES_REPO: Windows-on-ARM-Experiments/cygwin-packages
  CYGWIN_PACKAGES_BRANCH: ${{ inputs.cygwin_packages_branch || 'main' }}

  COCOM_REPO: git://git.code.sf.net/p/cocom/git
  COCOM_BRANCH: ${{ inputs.cocom_branch || 'master' }}

  OPENBLAS_REPO: OpenMathLib/OpenBLAS
  OPENBLAS_BRANCH: ${{ inputs.openblas_branch || 'develop' }}

  ZLIB_REPO: madler/zlib
  ZLIB_BRANCH: 'master'

  LIBXML2_REPO: GNOME/libxml2
# master branch contains an issue with va_list
# perhaps after changes in testapi.c
  LIBXML2_BRANCH: '2.14'

  OPENSSL_REPO: Windows-on-ARM-Experiments/openssl
  OPENSSL_BRANCH: ${{ inputs.openssl_branch || 'fix-tests' }}

  LIBJPEG_TURBO_REPO: libjpeg-turbo/libjpeg-turbo
  LIBJPEG_TURBO_BRANCH: 3.0.2

  FFMPEG_REPO: FFmpeg/FFmpeg
  FFMPEG_BRANCH: release/6.1

  BASH_REPO: Windows-on-ARM-Experiments/bash
  BASH_BRANCH: woarm64

  TOOLCHAIN_PATH: ${{ github.workspace }}/cross
  TOOLCHAIN_NAME: aarch64-w64-mingw32-msvcrt
  TOOLCHAIN_ARTIFACT_NAME: aarch64-w64-mingw32-msvcrt-toolchain
  TOOLCHAIN_PACKAGE_NAME: aarch64-w64-mingw32-msvcrt-toolchain.tar.gz
  RUNTIME_ARTIFACT_NAME: aarch64-w64-mingw32-msvcrt-toolchain
  RUNTIME_PACKAGE_NAME: aarch64-w64-mingw32-msvcrt-runtime.tar.gz

  SOURCE_PATH: ${{ github.workspace }}/code
  BUILD_PATH: ${{ github.workspace }}/build
  CCACHE_DIR_PATH: ${{ github.workspace }}/ccache
  ARTIFACT_PATH: ${{ github.workspace }}/artifact
  RELATIVE_ARTIFACT_PATH: ./artifact

  CCACHE: 1
  DELETE_BUILD: 1

jobs:
  build-toolchain:
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}

    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, x86_64]
        platform: [w64-mingw32, pc-linux-gnu, pc-cygwin]
        crt: [msvcrt, ucrt, libc]
        exclude:
          - platform: w64-mingw32
            crt: libc
          - platform: pc-linux-gnu
            crt: msvcrt
          - platform: pc-linux-gnu
            crt: ucrt
          - platform: pc-cygwin
            crt: ucrt
          - platform: pc-cygwin
            crt: libc
          - platform: pc-cygwin
            arch: aarch64

    env:
      ARCH: ${{ matrix.arch }}
      PLATFORM: ${{ matrix.platform }}
      CRT: ${{ matrix.crt }}
      PACK_TOOLCHAIN: ${{ matrix.arch == 'aarch64' && (matrix.platform == 'w64-mingw32' || matrix.platform == 'pc-cygwin') && matrix.crt == 'msvcrt' }}
      TOOLCHAIN_NAME: ${{ matrix.arch }}-${{ matrix.platform }}-${{ matrix.crt }}
      TOOLCHAIN_ARTIFACT_NAME: ${{ matrix.arch }}-${{ matrix.platform }}-${{ matrix.crt }}-toolchain
      TOOLCHAIN_PACKAGE_NAME: ${{ matrix.arch }}-${{ matrix.platform }}-${{ matrix.crt }}-toolchain.tar.gz
      RUNTIME_ARTIFACT_NAME:  ${{ matrix.arch }}-${{ matrix.platform }}-${{ matrix.crt }}-runtime
      RUNTIME_PACKAGE_NAME: ${{ matrix.arch }}-${{ matrix.platform }}-${{ matrix.crt }}-runtime.tar.gz
      TESTS_ARTIFACT_NAME: ${{ matrix.arch }}-${{ matrix.platform }}-${{ matrix.crt }}-tests
      TESTS_PACKAGE_NAME: ${{ matrix.arch }}-${{ matrix.platform }}-${{ matrix.crt }}-tests.tar.gz
      BUILD_ARTIFACT_NAME: ${{ matrix.arch }}-${{ matrix.platform }}-${{ matrix.crt }}-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}
          fetch-depth: 0

      - name: Get cache keys
        id: cache-keys
        run: |
          .github/scripts/get-cache-keys.sh

      - name: Cache toolchain
        id: cache-toolchain
        if: ${{ env.PACK_TOOLCHAIN == 'true' }}
        uses: actions/cache@v4
        with:
          path: ${{ env.RELATIVE_ARTIFACT_PATH }}/${{ env.TOOLCHAIN_PACKAGE_NAME }}
          key: ${{ steps.cache-keys.outputs.toolchain-cache-key }}
          enableCrossOsArchive: true

      - name: Cache runtime
        id: cache-runtime
        if: ${{ env.PACK_TOOLCHAIN == 'true' }}
        uses: actions/cache@v4
        with:
          path: ${{ env.RELATIVE_ARTIFACT_PATH }}/${{ env.RUNTIME_PACKAGE_NAME }}
          key: ${{ steps.cache-keys.outputs.runtime-cache-key }}
          enableCrossOsArchive: true

      - name: Checkout binutils
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.BINUTILS_REPO }}
          ref: ${{ env.BINUTILS_BRANCH }}
          path: ${{ env.SOURCE_PATH }}/binutils

      - name: Checkout GCC
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GCC_REPO }}
          ref: ${{ env.GCC_BRANCH }}
          path: ${{ env.SOURCE_PATH }}/gcc

      - name: Checkout MinGW
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform != 'pc-linux-gnu' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MINGW_REPO }}
          ref: ${{ env.MINGW_BRANCH }}
          path: ${{ env.SOURCE_PATH }}/mingw

      - name: Checkout Cygwin
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform == 'pc-cygwin' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CYGWIN_REPO }}
          ref: ${{ env.CYGWIN_BRANCH }}
          path: ${{ env.SOURCE_PATH }}/cygwin

      - name: Checkout Cygwin packages
        if: ${{ false && steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform == 'pc-cygwin' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CYGWIN_PACKAGES_REPO }}
          ref: ${{ env.CYGWIN_PACKAGES_BRANCH }}
          submodules: 'recursive'
          path: ${{ env.SOURCE_PATH }}/cygwin-packages

      - name: Checkout COCOM
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform == 'pc-cygwin' }}
        run: |
          cd ${{ env.SOURCE_PATH }}
          git clone ${{ env.COCOM_REPO }} -b ${{ env.COCOM_BRANCH }} cocom

      - name: Install dependencies
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        run: |
          .github/scripts/install-dependencies.sh

      - name: Install libraries
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        run: |
          .github/scripts/install-libraries.sh

      - name: Restore Ccache
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CCACHE_DIR_PATH }}
          key: ${{ steps.cache-keys.outputs.ccache-key }}
          restore-keys: ${{ steps.cache-keys.outputs.ccache-restore-keys }}

      - name: Build binutils
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        env:
          # Don't delete build files, they're needed for running binutils tests in the next step.
          DELETE_BUILD: 0
        run: |
          .github/scripts/binutils/build.sh

      - name: Execute binutils tests
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        run: |
          .github/scripts/toolchain/execute-binutils-tests.sh

      - name: Delete binutils build files
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && env.DELETE_BUILD == 1 }}
        run: |
          .github/scripts/binutils/delete-build.sh

      - name: Install cross headers and libraries
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform == 'pc-linux-gnu' }}
        run: |
          .github/scripts/toolchain/install-cross-headers-libs.sh

      - name: Build MinGW headers
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform != 'pc-linux-gnu' }}
        run: |
          .github/scripts/toolchain/build-mingw-headers.sh

      - name: Install Cygwin headers
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform == 'pc-cygwin' }}
        run: |
          .github/scripts/toolchain/install-cygwin-headers.sh

      - name: Build GCC stage1
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform != 'pc-linux-gnu' }}
        run: |
          .github/scripts/toolchain/build-gcc-stage1.sh

      - name: Build MinGW CRT
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform != 'pc-linux-gnu' }}
        run: |
          .github/scripts/toolchain/build-mingw-crt.sh

      - name: Build MinGW winpthreads
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform == 'w64-mingw32' }}
        run: |
          .github/scripts/toolchain/build-mingw-winpthreads.sh
  
      - name: Build COCOM
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform == 'pc-cygwin' }}
        run: |
          .github/scripts/toolchain/build-cocom.sh

      - name: Build Cygwin stage1
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform == 'pc-cygwin' }}
        run: |
          .github/scripts/toolchain/build-cygwin.sh 1

      - name: Build GCC stage2
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        run: |
          .github/scripts/toolchain/build-gcc.sh

      - name: Build MinGW
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform == 'w64-mingw32' }}
        run: |
          .github/scripts/toolchain/build-mingw.sh

      - name: Build Cygwin stage2
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform == 'pc-cygwin' }}
        run: |
          .github/scripts/toolchain/build-cygwin.sh 2

      - name: Save Ccache
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && always() }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CCACHE_DIR_PATH }}
          key: ${{ steps.cache-keys.outputs.ccache-key }}

      - name: Strip host binaries
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && matrix.platform != 'pc-linux-gnu' }}
        run: |
          .github/scripts/strip-host-binaries.sh

      - name: Pack toolchain
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && env.PACK_TOOLCHAIN == 'true' }}
        run: |
          .github/scripts/toolchain/pack.sh

      - name: Pack runtime
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && env.PACK_TOOLCHAIN == 'true' }}
        run: |
          .github/scripts/toolchain/pack-runtime.sh

      - name: Upload build folder
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          retention-days: 1
          path: ${{ env.BUILD_PATH }}

      - name: Upload toolchain artifact
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' && env.PACK_TOOLCHAIN == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TOOLCHAIN_ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}/${{ env.TOOLCHAIN_PACKAGE_NAME }}
          retention-days: 3

      - name: Upload runtime artifact
        if: ${{ steps.cache-runtime.outputs.cache-hit != 'true' && env.PACK_TOOLCHAIN == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RUNTIME_ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}/${{ env.RUNTIME_PACKAGE_NAME }}
          retention-days: 3

    outputs:
      toolchain-package-name: ${{ env.PACK_TOOLCHAIN == 'true' && env.TOOLCHAIN_PACKAGE_NAME || '' }}
      toolchain-artifact-name: ${{ env.PACK_TOOLCHAIN == 'true' && env.TOOLCHAIN_ARTIFACT_NAME || '' }}
      runtime-package-name: ${{ env.PACK_TOOLCHAIN == 'true' && env.RUNTIME_PACKAGE_NAME || '' }}
      runtime-artifact-name: ${{ env.PACK_TOOLCHAIN == 'true' && env.RUNTIME_ARTIFACT_NAME || '' }}
      toolchain-cache-key: ${{ env.PACK_TOOLCHAIN == 'true' && steps.cache-keys.outputs.toolchain-cache-key || '' }}
      aarch64-w64-mingw32-msvcrt-toolchain-cache-key: ${{ env.aarch64-w64-mingw32-msvcrt-toolchain-cache-key }}
      aarch64-pc-cygwin-msvcrt-toolchain-cache-key: ${{ env.aarch64-pc-cygwin-msvcrt-toolchain-cache-key }}
      runtime-cache-key: ${{ env.PACK_TOOLCHAIN == 'true' && steps.cache-keys.outputs.runtime-cache-key || '' }}
      aarch64-w64-mingw32-msvcrt-runtime-cache-key: ${{ env.aarch64-w64-mingw32-msvcrt-runtime-cache-key }}
      aarch64-pc-cygwin-msvcrt-runtime-cache-key: ${{ env.aarch64-pc-cygwin-msvcrt-runtime-cache-key }}
