name: Build toolchain

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      binutils_branch:
        description: 'Binutils branch to build'
        required: false
        default: 'woarm64'
      gcc_branch:
        description: 'GCC branch to build'
        required: false
        default: 'woarm64'
      mingw_branch:
        description: 'Mingw branch to build'
        required: false
        default: 'woarm64'
      check:
        description: 'Check if the toolchain is working'
        type: boolean
        required: false
        default: 'false'
env:
  BINUTILS_BRANCH: ${{ github.event.inputs.binutils_branch }}
  GCC_BRANCH: ${{ github.event.inputs.gcc_branch }}
  MINGW_BRANCH: ${{ github.event.inputs.mingw_branch }}

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential binutils-for-build texinfo bison flex zlib1g-dev libgmp-dev dejagnu libmpc-dev

      - name: Build
        run: |
          chmod +x ./build.sh
          bash ./build.sh
      
      - name: Check
        if: ${{ github.event.inputs.check }}
        run: |
          chmod +x ./check.sh
          bash ./check.sh
