name: Patch set test

on:
  workflow_dispatch:
  pull_request:

jobs:

  build-patch-series3-1:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'aarch64-patch-series3-v1'
      gcc_branch: '4012f1fc52a89c309d1ce965854b4edc625b6bca'
      mingw_branch: 'woarm64'

  build-patch-series3-2:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'aarch64-patch-series3-v1'
      gcc_branch: '5b6cb4738c5511203c359952c1a4a3aacb588502'
      mingw_branch: 'woarm64'

  build-patch-series3-3:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'aarch64-patch-series3-v1'
      gcc_branch: '66e14ac702dc6d696f54d2c66b82ca92a51f7032'
      mingw_branch: 'woarm64'

  build-patch-series3-4:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'aarch64-patch-series3-v1'
      gcc_branch: '4d76c321668ad7f6af42a03520b347841030a38d'
      mingw_branch: 'woarm64'

  build-patch-series3-5:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'aarch64-patch-series3-v1'
      gcc_branch: '2a2754012aafd698cca4fc55b7e5840217c393dd'
      mingw_branch: 'woarm64'

  build-patch-series3-6:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'aarch64-patch-series3-v1'
      gcc_branch: 'ee811afe6c7919bc149282d1e05c6890403e24f7'
      mingw_branch: 'woarm64'

  build-patch-series3-7:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'aarch64-patch-series3-v1'
      gcc_branch: '8dc423915287bc1ff8f2ff5026ea585b08c5ba03'
      mingw_branch: 'woarm64'

  build-patch-series3-8:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'aarch64-patch-series3-v1'
      gcc_branch: 'a6e0fed187a277d3293f0af59c652f06faf42be9'
      mingw_branch: 'woarm64'

  build-patch-series3-9:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'aarch64-patch-series3-v1'
      gcc_branch: '72b8976b791ce2cb71786f6f82524f96480920e8'
      mingw_branch: 'woarm64'
