name: Patch set test

on:
  workflow_dispatch:
  pull_request:

jobs:

  build-patch-series2-1:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'upstream'
      gcc_branch: '14746d103aabd1cdb6b5698f828922de55257fda'
      mingw_branch: 'aarch64-patch-stage2-v1'

  build-patch-series2-2:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'upstream'
      gcc_branch: '58decd8d7614a276e6c502fe1848f251eff9d6a4'
      mingw_branch: 'aarch64-patch-stage2-v1'

  build-patch-series2-3:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'upstream'
      gcc_branch: '5ec80f12120554b1d0e73203d82b5c9eda1ff56f'
      mingw_branch: 'aarch64-patch-stage2-v1'

  build-patch-series2-4:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'upstream'
      gcc_branch: '0bbb9b96bb823d0d624e03505de90e9014dc26bd'
      mingw_branch: 'aarch64-patch-stage2-v1'

  build-patch-series2-5:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'upstream'
      gcc_branch: '6701bca50eb48d2c179d4a95361ecc8e251c9ae1'
      mingw_branch: 'aarch64-patch-stage2-v1'

  build-patch-series2-6:
    uses: ./.github/workflows/build-only.yml
    with:
      binutils_branch: 'upstream'
      gcc_branch: 'ac9e7adcfe3bf85ab21ca6a9ee8acf19781b3b4b'
      mingw_branch: 'aarch64-patch-stage2-v1'
