name: Patch set test

on:
  workflow_dispatch:
  pull_request:

jobs:

  build-patch-set1-v6-1:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: '0f4c8e2591900f6fa93a79d9adacc26f8e59ed18'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-2:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: 'a4c37b802da4cd7ca792a41ad5c42f5b74b7b5be'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-3:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: '7d7444078e4a860c7eb130eab3050c3310127937'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-4:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: '3dcc4b7fae8b6dde8c74ad03a480ce6abefe654a'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-5:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: '37b6952de2f0acd678cf35224325a75bad1d0b46'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-6:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: '0a399a4040abad9f42b598ab4a3f581fbae6c830'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-7:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: 'b3a65043c5de240e78bd5c26bd920f4e7928a727'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-8:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: 'a924d9b0cd0e9c3747f685d9140687ae7cadaffa'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-9:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: 'a3dd7e850882137a1943637288eaf8c651b05117'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-10:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: '30888a967c78d21d23a4fa88486a046d44bd57ba'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-11:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: '83591f296e2c3e28ce9a5ad34c27fe2d944f634b'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-12:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: '7ff3c94546a80978a5c76e4a7230c382b428873f'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true

  build-patch-set1-v6-13:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: 'd5ba9fbebdf2fbaa6be30e62affe81e4496f1838'
      mingw_branch: 'aarch64-patch-min'
      validate_only_toolchain_build: true
