name: Patch set test

on:
  workflow_dispatch:
  pull_request:

jobs:

  build:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: 'cfd8e9b5319fda94f85ec013bd902b8cb58aefa8'
      mingw_branch: 'aarch64-patch-min'
