name: Patch set test

on:
  workflow_dispatch:
  pull_request:

jobs:

  build:
    uses: ./.github/workflows/advanced.yml
    with:
      binutils_branch: 'aarch64-patch-min'
      gcc_branch: 'aarch64-patch-min-3~15'
      mingw_branch: 'aarch64-patch-min'
